[package]
name = "histongram"
version = "0.1.0"
edition = "2021"

license = "MIT OR Apache-2.0"

repository = "https://github.com/tdittr/histongram"
authors = [
    "tdittr <td-github@orangecar.org",
]

[features]
default = ["fxhash"]
fxhash = ["dep:fxhash"]
serde = ["dep:serde"]

[dependencies]
fxhash = { version = "0.2.1", optional = true }
serde = { version = "1", optional = true }

[dev-dependencies]
insta = { version = "1.20.0", features = ["ron"] }
criterion = "0.4.0"

[[bench]]
name = "histogram"
harness = false