[package]
name = "histongram-python"
description = "Python bindings for histongram"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
histongram = { path = ".." }
pyo3 = "0.17.1"