name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cargo clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings --no-deps
      - name: Cargo test
        run: cargo test --workspace --all-targets --all-features
      - name: Cargo fmt
        run: cargo fmt --all -- --check